name: flutter_experiments
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.0
  fl_ass:
    path: packages/fl_ass
  image_generator:
    path: packages/image_generator

flutter:
  uses-material-design: true
  assets:
    - assets/images/
