name: flutter_experiments
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  copy_with_extension: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  meta: ^1.0.0
  validator:
    path: packages/validator

dev_dependencies:
  build_runner: ^2.0.0
  copy_with_extension_gen: ^4.0.0
  json_serializable: ^6.0.0
  validator_generator:
    path: packages/validator_generator

flutter:
  uses-material-design: true
