name: flutter_experiments
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  hello_generator:
    path: packages/hello_generator

flutter:
  uses-material-design: true
