name: flutter_experiments
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
