name: flutter_experiments
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Also update ios/Podfile with the version that
  # corresponds to the pod version used internally.
  cloud_firestore: ^3.0.0
  cloud_functions: ^3.0.0
  firebase_app_check: ^0.0.6
  firebase_auth: ^3.0.0
  firebase_core: ^1.0.0
  firebase_messaging: ^11.0.0
  flutter:
    sdk: flutter
  uuid: ^3.0.0

dev_dependencies:
  googleapis_auth: ^1.0.0
  http: ^0.13.0

flutter:
  uses-material-design: true
