name: flutter_experiments
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  firebase_app_check: ^0.0.6
  firebase_auth: ^3.0.0
  firebase_core: ^1.0.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
