builders:
  validator_generator:validator:
    import: package:validator_generator/builder.dart
    builder_factories:
      - validatorBuilder
    build_extensions:
      .dart:
        - .validator.g.part
    auto_apply: dependents
    build_to: cache
    applies_builders:
      - source_gen:combining_builder
