name: validator_generator
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  source_gen: ^1.0.0
  validator:
    path: ../validator
