builders:
  hello:
    import: package:hello_generator/builder.dart
    builder_factories:
      - helloBuilder
    build_extensions:
      .dart:
        - .hello.part
    auto_apply: dependents
    build_to: cache
    applies_builders:
      - hello_generator:_hallo_dart

  _hallo_dart:
    import: package:hello_generator/src/builder.dart
    builder_factories:
      - helloDartBuilder
    build_extensions:
      .hello.part:
        - .hello.dart
    build_to: source
    required_inputs:
      - .hello.part
