builders:
  hello:
    import: package:hello_generator/builder.dart
    builder_factories:
      - helloBuilder
    build_extensions:
      .dart:
        - .hello
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude:
          - '**/*_*.dart'
      options:
        greeting: Hola
