builders:
  hello:
    import: package:hello_generator/builder.dart
    builder_factories:
      - helloBuilder
    build_extensions:
      .dart:
        - .hello.part
    auto_apply: dependents
    build_to: cache
    applies_builders:
      - hello_generator:_hello_collector

  _hello_collector:
    import: package:hello_generator/src/builder.dart
    builder_factories:
      - helloCollectorBuilder
    build_extensions:
      $package$:
        - lib/hello.gen.dart
    build_to: source
    required_inputs:
      - .hello.part
